node_js:
  - "node"

script:
- echo “Vérification du style avec jshint”
- npm install jshint --save-dev
- node_modules/.bin/jshint src
- echo “Exécution des tests”
- npm install
- npm test

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $tokenDeploie
  keep_history: true
  on:
    branch: master
